POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "new academic year",
    "author": "Philip Muller",
    "url": "http://foo.bar",
    "likes": 32,
    "userId": "63b2e4d3d2ed5da24202bd23"
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "roote",
    "password": "first_secret"
}